services:
  dev-bob-robot:
    image: bob-robot:latest
    container_name: dev-bob-robot
    ports:
      - "6512:8080"
      - "6513:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: unless-stopped
